### ISSUE TITLE
Xiaomi - Bootloop when updating to newer version

### ISSUE THREAD

**Issue by lp55** [lineageos4microg/android_prebuilts_prebuiltapks#19] opened 2019-08-05 10:51 UTC
Hi,

    When I tried installing on tissot a version newer than lineage-16.0-20190724-microG-tissot it doesn't work, and if I install this version it works fine, but if I try to do a OTA update afterwards I get a bootloop, which is only fixed by flashing the older version. I saw an issue about bootloop [here](https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/issues/13) but it says it was fixed, so I image this is another issue.
    Other than that, LineageOS + microG is great :)

**Comment by Ezwen** [comment] 2019-08-17 14:23
I tried to make a fresh install of the last version of lineage-microg on a Xiaomi Mix 2 (chiron), which is `lineage-16.0-20190805-microG-chiron.zip`, but I end up stuck on the bootloader splash. Maybe this is a similar problem?

EDIT: I also encountered this problem when following the official guide to migrate from a vanilla Lineage OS 16.0 to a lineage-microg build.

**Comment by ghost** [comment] 2019-08-22 15:11
This also happens with a clean installation.

**Comment by lp55** [comment] 2019-08-23 11:12
Hi,

   Have any of the developers been able to reproduce this issue? Can I upgrade to the latest version and not have my os stuck on boot loop?
    Thanks

**Comment by ghost** [comment] 2019-08-30 12:01
@corna 

Have you looked into this? This doesn't happen on default LineageOS.

**Comment by corna** [comment] 2019-09-03 05:12
A week ago (a couple of days before the DCMA removal) our TheMuppets/xiaomi repo went out of sync, which caused a lot of issues for many Xiaomi devices. For now I'll just remove the broken images, I'll try to see if the issue is solved as soon as the TheMuppets repo comes back.
If you experience issues with other XIaomi smartphones, let me know here.

**Comment by Korsola** [comment] 2019-09-14 19:07
> A week ago (a couple of days before the DCMA removal) our TheMuppets/xiaomi repo went out of sync, which caused a lot of issues for many Xiaomi devices. For now I'll just remove the broken images, I'll try to see if the issue is solved as soon as the TheMuppets repo comes back.
> If you experience issues with other XIaomi smartphones, let me know here.

@corna 
While waiting for the TheMuppets repo to come back, couldn't you use @Crescendo-BLYAT's re-uploaded Xiaomi repo?
https://github.com/Crescendo-BLYAT/proprietary_vendor_xiaomi

This will fix the issue before TheMuppets repo comes back as it may take a while.

**Comment by ghost** [comment] 2019-09-18 08:30
https://www.xda-developers.com/lineageos-builds-back-online-xiaomi-devices/

**Comment by ghost** [comment] 2019-09-19 04:27
@corna 
Now the Xiaomi Mi A1 LineageOS build is back again.

**Comment by Iey4iej3** [comment] 2019-09-26 07:15
@corna For the moment, none of Xiaomi builds of LOS for microG is back, while official LOS builds were back a week ago. I am pretty confused since it seems to me that we handle the collection of build targets manually instead of automatically tracing [build targets of official Lineage OS](https://github.com/LineageOS/hudson/blob/master/lineage-build-targets)? Xiaomi builds were [removed](https://github.com/LineageOS/hudson/commit/7c87ce6a895d9aebfc1c79ba43e8bc34be0426af#diff-6e2d6eaccc424d5936d22f65ce8b37bd) and recently [back](https://github.com/LineageOS/hudson/commit/10304a02ce1e792c85e01aca916fa63e4bef5e68#diff-6e2d6eaccc424d5936d22f65ce8b37bd) but builds of LOS for microG do not synchronize with that?

By the way, several users on xda and reddit suggest public build log. Is that possible?

**Comment by corna** [comment] 2019-09-26 07:19
The problem is that https://github.com/TheMuppets/proprietary_vendor_xiaomi is still down, so the automatic builds failed. I will have a look to see if I can make them succeed.

**Comment by Iey4iej3** [comment] 2019-09-26 07:29
@corna Thanks for a very rapid reply. I think it is better to ask LineageOS Team to understand how they came up with a solution, after all they succeeded to build.

**Comment by corna** [comment] 2019-09-26 07:31
They probably have their own internal TheMuppets mirror, from which they have removed the problematic components. However it is proprietary code in a grey area, so it is unlikely that they will provide us access to that repo.

**Comment by Iey4iej3** [comment] 2019-09-26 07:43
Theoretically we can extract blobs from LOS nightly builds, but it is pretty treating and maybe unpleasant. Seemingly better to ask them anyway. In the news, it is worded as "The branch containing Xiaomi device BLOBs was taken offline while the LineageOS team *looked for* an alternative". I think that it is very unlikely that you could work this out on your own without their indications or even helps, given that they spent a month solving this issue.

**Comment by ghost** [comment] 2019-09-26 10:51
> They probably have their own internal TheMuppets mirror, from which they have removed the problematic components. However it is proprietary code in a grey area, so it is unlikely that they will provide us access to that repo.

@corna 

https://gitlab.com/the-muppets/proprietary_vendor_xiaomi
This is the "new" TheMuppets repo that you can use. LineageOS also uses it.

Tagging also @Iey4iej3 just in case you are interested.

**Comment by corna** [comment] 2019-09-26 11:14
@Korsola Thank you, I wasn't aware of that repo.
I just have to assert somehow the authenticity of that repo, then I can add it to our mirror.

**Comment by ghost** [comment] 2019-09-26 12:24
> I just have to assert somehow the authenticity of that repo

I found the repo via recognized contributor's khusika's comment on XDA. He's a well-known person. He commented the following:

> As far as i know the Xiaomi vendor files are now migrate to the gitlab
> https://gitlab.com/the-muppets/propr..._vendor_xiaomi

https://forum.xda-developers.com/mi-a1/development/rom-lineageos-16-0-xiaomi-mi-a1-t3885100/post80251862#post80251862

I'm also sure that if you contact LineageOS Team about the authenticity of the repo, they will answer.

**Comment by Korsola** [comment] 2019-09-26 12:24
> I just have to assert somehow the authenticity of that repo

I found the repo via recognized contributor's khusika's comment on XDA. He's a well-known person. He commented the following:

> As far as i know the Xiaomi vendor files are now migrate to the gitlab
> https://gitlab.com/the-muppets/propr..._vendor_xiaomi
https://forum.xda-developers.com/mi-a1/development/rom-lineageos-16-0-xiaomi-mi-a1-t3885100/post80251862#post80251862

I'm also sure that if you contact LineageOS Team about the authenticity of the repo, they will answer.

**Comment by corna** [comment] 2019-09-26 14:29
I have compared the old themuppets/proprietary_vendor_xiaomi with the one that you have linked and it appears that they have rewritten the (now) 9106d91a commit (and the history after that), removing a single file containing a license file related to a "FaceAuth" product from SenseTime, which matches the [DCMA complaint on GitHub](https://github.com/github/dmca/blob/master/2019/08/2019-08-09-SenseTime-5.md). Funny, a single 2kB license file caused the removal of all the Xiaomi devices for almost two months.

Anyways, the repo seems legit, let me dig a bit deeper and then I'll add it to our build system.

**Comment by Iey4iej3** [comment] 2019-09-27 06:58
I would like to suggest publicizing in some degree build logs or details of building process. As a [reddit post](https://www.reddit.com/r/MicroG/comments/d6di80/are_xiaomi_builds_coming_back/f1ax1oa?utm_source=share&utm_medium=web2x) suggests, ArrowOS has some machinery to do so. It would probably help you and us understand where issues situate. For example, berkeley is [missing](https://github.com/lineageos4microg/docker-lineage-cicd/issues/53) and we still don't know why. By publicizing, maybe somebody will figure out the obstruction.

**Comment by Iey4iej3** [comment] 2019-09-28 09:06
@corna Does it work as expected? If so, then we can inform the OP and close this issue.

**Comment by corna** [comment] 2019-09-28 09:07
I've tried to build for dipper but it failed with a different error, I still have to look at it.

**Comment by Iey4iej3** [comment] 2019-09-28 09:26
@corna In general, it seems better if we can cooperate better with Lineage OS Team. Do you know that recent Lineage OS builds (maybe only of Xiaomi devices?) ship with OSS vendor images? I don't know where is an official claim, but [here](https://gitlab.com/LineageOS/issues/android/issues/816#note_211260329) is an answer from a maintainer. (By the way, I am suffering from a similar issue therefore I am waiting for a new build with OSS vendor images.)

**Comment by corna** [comment] 2019-09-29 18:17
> Do you know that recent Lineage OS builds (maybe only of Xiaomi devices?) ship with OSS vendor images?

Yes, I have noticed the extra vendor partition in the zips but I haven't got the time to dig.

I have built LineageOS for microG for `dipper` with the Gitlab's The-Muppets repo and everything seems to work nicely. I'll try to contact the LineageOS team to obtain more guarantees on the authenticity of that repo, then I'll merge the patches and restart the builds for the Xiaomi devices.

**Comment by ghost** [comment] 2019-09-29 18:42
> I'll merge the patches and restart the builds for the Xiaomi devices.

Will the build(s) normally come via OTA update?

**Comment by corna** [comment] 2019-09-29 20:00
Yes

**Comment by Iey4iej3** [comment] 2019-10-01 10:12
After having received confirmations from LineageOS Team, I think that we can close this issue.

**Comment by ghormoon** [comment] 2019-10-01 11:23
is there another one to watch for when the builds will be back online? if not, why not keep it until they are?

**Comment by Iey4iej3** [comment] 2019-10-05 07:19
@corna Did you receive any official confirmations from Lineage OS Team? I believe that [bgcngm](https://forum.xda-developers.com/member.php?u=455439) works for various Xiaomi devices.

**Comment by corna** [comment] 2019-10-05 08:58
I have already tried to contact bgcngm, but I have received no reply.
I have added the GitLab repository to the docker build scripts, new Xiaomi builds shoud come soon.

**Comment by Algram** [comment] 2019-10-05 19:09
@corna Thanks for working on this. Is it possible that `chiron` and `polaris` are both still failing? Do you know of any reason?

EDIT: Nevermind, `polaris` just showed up.

**Comment by ghost** [comment] 2019-10-06 05:48
@corna 
`tissot` isn't showing up. Is it failing or is there another reason?

**Comment by corna** [comment] 2019-10-06 07:29
@AnthonyKL I forgot to include it in the manual build, doing it now ;)

**Comment by Iey4iej3** [comment] 2019-10-06 08:12
`polaris` works now. Thanks for your efforts. Wait for the OP to confirm, and then this issue could be closed.

**Comment by ghost** [comment] 2019-10-06 11:59
@corna 

My device is `tissot`. The OTA update to `lineage-16.0-20191006-microG-tissot` worked flawlessly. So I think the OP's issue is solved.

But the OTA Updater shows `lineage-16.0-20191006-microG-tissot.zip` build is available even though it is already installed? Can anyone else confirm this? Referencing to this (closed) issue:
https://github.com/lineageos4microg/docker-lineage-cicd/issues/59

Also an off-topic question, is it normal for "Android security patch level" to show September on October build?

**Comment by lp55** [comment] 2019-10-06 19:26
> @corna
> 
> My device is `tissot`. The OTA update to `lineage-16.0-20191006-microG-tissot` worked flawlessly. So I think the OP's issue is solved.

Hi my device is also a tissot (Mi A1) and it didn't event show the lineage boot logo before it rebooted. I had to go back to lineage-16.0-20190724-microG-tissot.

**Comment by andreev-fn** [comment] 2019-10-07 15:44
I have a tissot too. And I have bootloop on all versions after 20190320, haha.
Think deal can be in firmware, on weekends stuck roll back on the latest stock.
Has anyone encountered this?

**Comment by Iey4iej3** [comment] 2019-10-07 18:32
@lp55 @simplefied Do you encounter similar bootloops in [official LOS builds](https://download.lineageos.org/tissot)?

**Comment by braniii** [comment] 2019-10-07 21:07
> Also an off-topic question, is it normal for "Android security patch level" to show September on October build?

This is normal. The bulletin is always published on the first Monday in a month, so in this case today [October bulletin](https://source.android.com/security/bulletin/2019-10-01). Further, it can takes roughly up to 7 days (at least for an older Android version like LOS 16) to be merged into LOS. Having only weekly builds, you should only wonder if it is not merged by the mid to end of the month. Or you can check the changelogs, e.g. [here](https://review.lineageos.org/q/branch:+lineage-16.0++repo:LineageOS/android+manifest+android).

**Comment by andreev-fn** [comment] 2019-10-08 14:44
> @lp55 @simplefied Do you encounter similar bootloops in [official LOS builds](https://download.lineageos.org/tissot)?

I tried. Hmmm, official LOS 20191006 works fine. So it's not the firmware?

**Comment by andreev-fn** [comment] 2019-10-08 15:18
Haha, after official LOS had to wipe cache, data and system. BUT. After this latest LOS for microG works fine, bootloop disappear. Thanks!

**Comment by ghost** [comment] 2019-10-08 17:59
> Hi my device is also a tissot (Mi A1) and it didn't event show the lineage boot logo before it rebooted. I had to go back to lineage-16.0-20190724-microG-tissot.

@lp55 

Please flash the latest stock firmware/build [from here](https://t.me/s/notify4twrprom) and then clean flash the latest [LineageOS for microG build](https://download.lineage.microg.org/tissot/).

**Comment by ghost** [comment] 2019-10-08 18:14
Hey, @simplefied 

Could you confirm that are you experiencing the problem that I'm experiencing?

> But the OTA Updater shows `lineage-16.0-20191006-microG-tissot.zip` build is available even though it is already installed? Can anyone else confirm this? Referencing to this (closed) issue:
> [lineageos4microg/docker-lineage-cicd#59](https://github.com/lineageos4microg/docker-lineage-cicd/issues/59)

**Comment by Iey4iej3** [comment] 2019-10-08 19:00
> Hey, @simplefied
> 
> Could you confirm that are you experiencing the problem that I'm experiencing?
> 
> > But the OTA Updater shows `lineage-16.0-20191006-microG-tissot.zip` build is available even though it is already installed? Can anyone else confirm this? Referencing to this (closed) issue:

It seems to me that this is deliberate by design. As far as I remember, I encounter the same situation since long before (I cannot remember even whether that was in cyanogenmod).

**Comment by andreev-fn** [comment] 2019-10-09 12:51
Hi, @ghost
I confirm.
https://ibb.co/64zN25g

**Comment by ghost** [comment] 2019-10-23 16:27
@corna 
I think this issue can be closed now as the recent versions are working now.

**Closed as completed** 2020-08-14 13:56 UTC
